### ISSUE TITLE
Remove usage of replace

### ISSUE THREAD

**Issue by marbar3778** [corestario/cosmos-sdk#8]
## Summary

Currently, usage of `replace` causes the user to have all the repos in one directory. Not sure if there is a reason for this?

## Proposal

remove usage of replace so the end-user doesn't have to clone all the repos

should be done for all repos.

____

#### For Admin Use

- [x] Not duplicate issue
- [ ] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by zavgorodnii** [comment]
Hi! We have fixed this issue, now you can simjply clone the randapp repository and all dependencies will be resolved correctly.

**Comment by vshvsh** [comment]
Need to fix demo docs still.

**Comment by tac0turtle** [comment]
It doesn't this has been solved. Replace is still being used in most of the go.mods. not sure if there is a specific reason to do this?

**Comment by zavgorodnii** [comment]
O.K., we will remove replaces and switch to using our own repos explicitly.

**Comment by tac0turtle** [comment]
talked briefly to Vasiliy, he explained the reasoning. Makes sense, I think it is fine as it is. Sorry for confusion

**Comment by zavgorodnii** [comment]
that's wonderful!

**Comment by vshvsh** [comment]
For clarification, the reasoning is that it's a minor decision that was made to make pulling upstream and pushing upstream, if need be, slightly easier.
